### ISSUE TITLE
Navigation bar items

### ISSUE THREAD

**Issue by vlkvch** [nuxshed/nuxshed.github.io#1]
### Overview
The distance between the items in the navigation bar is different, when "Blog" is open, therefore there's no consistency.

### Home
![image](https://user-images.githubusercontent.com/82259360/151612783-98e40809-2a1f-4495-9303-e639738a6177.png)

### Blog
![image](https://user-images.githubusercontent.com/82259360/151612858-dfcc0f48-2410-477f-a2fa-a2d62c63a3af.png)

### Possible solution
You can move each link to a new line [here](https://github.com/nuxshed/nuxshed.github.io/blob/5a963ab65b901e3c333df4d4869ef87c7040568e/blog/index.html#L200).

**Comment by vlkvch** [comment]
I guess, the difference is barely visible on those screenshots. Here's a better explanation:
### Home
![Group 3](https://user-images.githubusercontent.com/82259360/151819811-030fb966-7a3d-4613-a366-6c67f6f2891c.png)
### Blog
![Group 4](https://user-images.githubusercontent.com/82259360/151819904-e09af903-7e09-479f-a50d-a59f86f82aac.png)

**Comment by nuxshed** [comment]
thanks for reporting this (and for the fix)!
